services:
  ibeam:
    image: adamlechnos/ibeam
    container_name: ibeam
    env_file:
    - env.list.ibeam
    ports:
      - 5000:5000
      - 5001:5001
    network_mode: bridge # Required due to clientportal.gw IP restrictions
    restart: 'no' # Prevents IBEAM_MAX_FAILED_AUTH from being exceeded
    volumes:
      - util-data:/srv/ibeam/util-data
  ibkr-create-website:
  # image: voyz/ibeam
    depends_on:
      - ibeam
    image: adamlechnos/ibkr-create-website
    container_name: ibkr-api-parser
    env_file:
      - env.list.parser
    network_mode: bridge # Required due to clientportal.gw IP restrictions
    restart: unless-stopped # Prevents IBEAM_MAX_FAILED_AUTH from being exceeded
    volumes:
      - util-data:/var/ibkr/util-data
      - web-data:/usr/src/app/webserver
  ibkr-dashboard-nginx:
    depends_on:
      - ibkr-create-website
    image: adamlechnos/ibkr-dashboard-nginx
    container_name: ibkr-dashboard-nginx
    env_file:
      - env.list.dashboard
    ports:
      - 8443:8443
    network_mode: bridge # Required due to clientportal.gw IP restrictions
    restart: 'no' # Prevents IBEAM_MAX_FAILED_AUTH from being exceeded
    volumes:
      # Uncomment below to specify TLS cert/key files
      - type: bind
        source: ./server.crt
        target: /usr/src/app/server.crt
      - type: bind
        source: ./server.key
        target: /usr/src/app/server.key
      - type: bind
        source: ./default.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: ./.htpasswd
        target: /etc/nginx/.htpasswd
      - util-data:/var/ibkr/util-data
      - web-data:/usr/src/app/webserver
  ibkr-push-gdrive:
  # image: voyz/ibeam
    depends_on:
      - ibkr-create-website
    image: adamlechnos/ibkr-push-gdrive
    container_name: ibkr-push-gdrive
    env_file:
      - env.list.gdrive
    stdin_open: true
    tty: true
    network_mode: bridge # Required due to clientportal.gw IP restrictions
    restart: 'no' # Prevents IBEAM_MAX_FAILED_AUTH from being exceeded
    volumes:
      - type: bind
        source: ./client_secrets.json
        target: /usr/src/app/client_secrets.json
      - type: bind
        source: ./mycreds.txt
        target: /usr/src/app/mycreds.txt
      - web-data:/usr/src/app/webserver
volumes:
  util-data:
  web-data: